version: '3'

services:
  mysql-springboot:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tracker
      - MYSQL_USER=vishal
      - MYSQL_PASSWORD=test
  emsspringmaster:
    image: emsspringmaster
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-springboot:3306/tracker?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "vishal"
      SPRING_DATASOURCE_PASSWORD: "test"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-springboot
