# For dockerfile
# This below datasource will not required if we pass environment in docker-compose
spring:
  datasource:
    url: jdbc:mysql://mysql-springboot:3306/tracker?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: vishal
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
