spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp_tracker
    username: root
    password: test


## For dockerfile
#spring:
#  datasource:
#    url: jdbc:mysql://mysql-springboot:3306/tracker
#    username: vishal
#    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

