spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp_tracker
    username: root
    password: test
#    url: jdbc:mysql://mysql-db:3306/tracker
#    username: vishal
#    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9090
