spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp_tracker
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

## MULTIPART (MultipartProperties)
# Enable multipart uploads
  servlet:
   multipart:
    enabled: true
  # Threshold after which files are written to disk.
    file-size-threshold: 2KB
  # Max file size.
    max-file-size: 200MB
  # Max Request Size
    max-request-size: 215MB

  ## File Storage Properties
  # All files uploaded through the REST API will be stored in this directory

  profiles:
    active: default

# this will create new folder inside root directory
file:
  storage:
    location: uploads

logging:
  level:
    com.employetracker: trace
  file:
    path: E:/logging ems


